# 一. Python特色 
- 縮排結構
- 不須宣告變數類型
- 序列操作
    - 儲存型態
        - 容器 : 儲存不同型態項目 ex. list, tuple...
        - 一般 : 只能儲存最基本資料如數字、字元 ex. str, bytes
    - 序列可變與否
        - 可變 ex. list
        - 不可變 ex. tuple
- 物件導向語言



### 靜態型別 : 對每個變數明確宣告變數類型    ex.C, JAVA

### 動態型別 : 彈性的指定任意型態資料給變數 ex.Python

In [1]:
x = 'Bob'
print(x)
print(type(x))

Bob
<class 'str'>


In [1]:
my_list = [2,'NCCU',True]
my_list

[2, 'NCCU', True]

### integer包含4個部分
- ob_refcnt，參考計數，協助python處理記憶體的解除和配置
- ob_type，變數型態編碼
- ob_size，指出成員大小
- ob_digit，儲存Python變數中表示的實際數值

List優點為彈性，Array固定型態陣列缺乏彈性，但儲存和操作資料有效率

# 二. list, tuple
### 賦值 : 盒子vs標籤

In [2]:
a = [1,2,3]
b = a
a.append(4)
# http://www.pythontutor.com/

In [3]:
a

[1, 2, 3, 4]

In [4]:
b

[1, 2, 3, 4]

In [5]:
print(a==b)   #比較"值"
print(a is b) #比較"身分"

True
True


In [6]:
print(id(a))
print(id(b))

2409520905672
2409520905672


### tuple的不可變性
不可變性質指的是資料結構的物理內容


In [7]:
t1 = (1,2,[3,4])
t2 = (1,2,[3,4])
print(t1==t2)    
print(t1 is t2)

True
False


In [8]:
t1[2].append(5)
print(t1)

(1, 2, [3, 4, 5])


### 串列淺層複製

In [10]:
l1 = [3,[5,4],(7,8,9)]
l2 = list(l1)

print(l1==l2)
print(l1 is l2)

True
False


In [ ]:
l1.append(10)
l1[1].remove(5)
l2[1] += [11,12]
l2[2] += (13,14)
print(l1)
print(l2)

# 三. Numpy

### 1.子陣列為未複製的視圖，非 複製 的陣列

In [12]:
import numpy as np

my_array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(my_array)
my_array_sub = my_array[0:2,0:2]
print(my_array_sub)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2]
 [5 6]]


In [14]:
my_array_sub[0][0] = 66

In [17]:
print(my_array_sub)
print(my_array)

[[66  2]
 [ 5  6]]
[[66  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
my_array_sub2 = my_array[:2,:2].copy()
my_array_sub2[0][0] = 77
print(my_array_sub2)
print(my_array_sub)

[[77  2]
 [ 5  6]]
[[66  2]
 [ 5  6]]


### 2.Universal Functions(ufuncs)
####   陣列快速運算關鍵 : 向量化操作

In [21]:
def reciprocal(values):
    output=np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1/values[i]
    return output

In [22]:
np.random.seed(0)
my_value = np.random.randint(1,10,size=100000)

print(my_value)
print(reciprocal(my_value))

[6 1 4 ... 7 6 6]
[0.16666667 1.         0.25       ... 0.14285714 0.16666667 0.16666667]


#### 執行時間

In [23]:
%time reciprocal(my_value)

Wall time: 33.9 ms


array([0.16666667, 1.        , 0.25      , ..., 0.14285714, 0.16666667,
       0.16666667])

In [24]:
%timeit reciprocal(my_value)

33 ms ± 3.14 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [25]:
my_value_array = np.array(my_value)
%timeit(1/my_value_array)

137 µs ± 790 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### 聚合操作
常見 : 總和、乘積、中位數、最大值、最小值...

In [27]:
num_array = np.random.rand(100)

print(sorted(num_array))   #內建涵式
print(np.sort(num_array))  #numpy內的涵式
print(num_array.sort())    #物件本身的方法

[0.013609987359720521, 0.02408740373634599, 0.032479874285764265, 0.03411298619323655, 0.03548055687853957, 0.03985921145223226, 0.04775741890546137, 0.06127445382055541, 0.06208132859270021, 0.09031004873915871, 0.10344278054867728, 0.10646188897364606, 0.11721582599971692, 0.15424698172981732, 0.1600004496429841, 0.1706913072802242, 0.17752475578574944, 0.1800218251503396, 0.1828612741702803, 0.187285779558913, 0.1894457679040017, 0.2107034067002097, 0.21711397453399817, 0.21914529294194796, 0.22148527679548602, 0.2317326941934721, 0.2657885461833348, 0.297833545863163, 0.3254548207107911, 0.34873991622462686, 0.3609224081732546, 0.36137118970031123, 0.3780370273243343, 0.3814064390193005, 0.38512150931464695, 0.3891916879594133, 0.3942560948239139, 0.41065265160869213, 0.41436963657117964, 0.4336185578087688, 0.4439495028230661, 0.4571179609867375, 0.4581248247605051, 0.4605120946198902, 0.4695855065554895, 0.49490781488814717, 0.5063815107795017, 0.520151290053754, 0.54689052961348

In [28]:
%timeit sorted(num_array) 

7.58 µs ± 191 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [29]:
%timeit np.sort(num_array)

2.26 µs ± 45.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [30]:
%timeit num_array.sort()

664 ns ± 9.82 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### 陣列上的計算 : Broadcasting

In [31]:
a = np.arange(3)
print(a)
print(a.shape)

[0 1 2]
(3,)


In [32]:
b = np.ones((2,3))
print(b)
print(b.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


#### 規則一 : 若兩陣列維度不同，低維度陣列被用作墊充

In [35]:
print(a+b)
print(a)
print(b)
#(3,)+(2,3) -> (1,3)+(2,3) ->(2,3)+(2,3)

[[1. 2. 3.]
 [1. 2. 3.]]
[0 1 2]
[[1. 1. 1.]
 [1. 1. 1.]]


#### 規則二(兩者皆須broadcasting) : 兩陣列任一維度皆不符合，具有形狀1的那一維要被拉長到符合另一陣列形狀

In [36]:
c = a.reshape((3,1))
print(c)
print(c.shape)

[[0]
 [1]
 [2]]
(3, 1)


In [37]:
print(a)
print(c)
print(a+c)
#(3,)+(3,1) -> (1,3)+(3,1) -> (3,3)+(3,3)

[0 1 2]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 規則三 : 若兩陣列不能在任一維度符合，也沒有任一個維度大小等於一，則無法執行

In [38]:
d = np.ones((3,2))
print(d)
print(d.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
(3, 2)


In [39]:
a+d
#(3,)+(3,2) -> (1,3)+(3,2) -> (3,3)+(3,2)

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [40]:
a[:,np.newaxis]+d.reshape((3,2))
#(3,)+(3,2) -> (3,1)+(3,2) -> (3,2)+(3,2)

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

# 四. 模組(module)

In [ ]:
import sys
for place in sys.path:
    print(place)

In [ ]:
import report as rp
rp.get_descripition()

In [ ]:
import today_weather

- 套件(Packages)
    - 模組1(module1)
        - abc.py
        - def.py
    - 模組2(module2)
        - ghi.py

許多模組時可建立目錄

In [ ]:
from sources import daily, weekly

print(daily.forecast())
print(weekly.forecast())